// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:dc58f5e1-7cb1-4f31-80f2-7cf4919cdafa",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_wR2F4nae3",
    "aws_user_pools_web_client_id": "3tqauj8f2j1fm5stvtnmq1e5fi",
    "aws_appsync_graphqlEndpoint": "https://ovvqlkaajnd3jn2fw6ob5hgyba.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "appsyncrekoa4933c54c834489faf17cbcef50e4f36",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
